functionsDirectory = "/home/clawbotpi/sites/safehandsautocare/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/clawbotpi/sites/safehandsautocare"
publishOrigin = "ui"
functions = "/home/clawbotpi/sites/safehandsautocare/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]